/* === Widya-Lang Standalone Native / Mobile Bundle === */
/* Generated automatically by 'widya kemas' */

// Auto-generated by Widya Native Compiler
#![allow(unused_variables, unused_mut, non_snake_case, dead_code, unused_macros, unreachable_code, unused_parens)]

trait WidyaDisplay {
    fn widya_display(&self) -> String;
}
impl<T: std::fmt::Debug> WidyaDisplay for T {
    fn widya_display(&self) -> String {
        let s = format!("{:?}", self);
        if s.starts_with('"') && s.ends_with('"') && s.len() >= 2 {
            s[1..s.len()-1].to_string()
        } else {
            s
        }
    }
}

macro_rules! cetak {
    ($($arg:expr),* $(,)?) => {{
        let parts: Vec<String> = vec![$( ($arg).widya_display() ),*];
        println!("{}", parts.join(" "));
    }};
}
macro_rules! tulis {
    ($($arg:expr),* $(,)?) => {{
        let parts: Vec<String> = vec![$( ($arg).widya_display() ),*];
        print!("{}", parts.join(" "));
    }};
}

fn akar(x: f64) -> f64 { x.sqrt() }
fn bulat(x: f64) -> f64 { x.round() }
fn lantai(x: f64) -> f64 { x.floor() }
fn atap(x: f64) -> f64 { x.ceil() }
fn mutlak(x: f64) -> f64 { x.abs() }
fn ke_teks<T: std::fmt::Display>(v: T) -> String { format!("{}", v) }
fn ke_angka(v: &str) -> f64 { v.trim().parse::<f64>().unwrap_or(0.0) }
fn tipe<T>(_: T) -> &'static str { "nilai" }
fn panjang<T>(v: &[T]) -> f64 { v.len() as f64 }
fn tambah<T: Clone>(v: &mut Vec<T>, item: T) { v.push(item); }

fn main() {
    cetak!("=== ⚡ 1. Komputasi Vektorisasi Berkecepatan Tinggi (WidyaSIMD) ===".to_string());
    let mut v1 = VektorF32x4(10.0_f64, 20.0_f64, 30.0_f64, 40.0_f64);
    let mut v2 = VektorF32x4(2.0_f64, 3.0_f64, 4.0_f64, 5.0_f64);
    cetak!(((((((("Vektor A: ".to_string() + string(v1["x".to_string() as usize])) + ", ".to_string()) + string(v1["y".to_string() as usize])) + ", ".to_string()) + string(v1["z".to_string() as usize])) + ", ".to_string()) + string(v1["w".to_string() as usize])));
    cetak!(((((((("Vektor B: ".to_string() + string(v2["x".to_string() as usize])) + ", ".to_string()) + string(v2["y".to_string() as usize])) + ", ".to_string()) + string(v2["z".to_string() as usize])) + ", ".to_string()) + string(v2["w".to_string() as usize])));
    let mut v_tambah = simd_tambah(v1, v2);
    let mut v_kali = simd_kali(v1, v2);
    let mut hasil_dot = simd_dot(v1, v2);
    let mut jarak = simd_jarak(v1, v2);
    cetak!(((((((("Hasil SIMD Tambah (A + B): ".to_string() + string(v_tambah["x".to_string() as usize])) + ", ".to_string()) + string(v_tambah["y".to_string() as usize])) + ", ".to_string()) + string(v_tambah["z".to_string() as usize])) + ", ".to_string()) + string(v_tambah["w".to_string() as usize])));
    cetak!(((((((("Hasil SIMD Kali (A * B): ".to_string() + string(v_kali["x".to_string() as usize])) + ", ".to_string()) + string(v_kali["y".to_string() as usize])) + ", ".to_string()) + string(v_kali["z".to_string() as usize])) + ", ".to_string()) + string(v_kali["w".to_string() as usize])));
    cetak!(("SIMD Dot Product: ".to_string() + string(hasil_dot)));
    cetak!(("SIMD Jarak Euclidean (||A - B||): ".to_string() + string(jarak)));
    let mut daftar_vektor = simd_ke_daftar(v_tambah);
    cetak!(("Larik standar dari SIMD: ".to_string() + string(daftar_vektor)));
    cetak!("=== 🚀 Selesai Menjalankan SIMD & JIT Demo ===".to_string());
}
