/* === Widya-Lang Standalone Native / Mobile Bundle === */
/* Generated automatically by 'widya kemas' */

// Auto-generated by Widya Native Compiler
#![allow(unused_variables, unused_mut, non_snake_case, dead_code, unused_macros, unreachable_code, unused_parens)]

trait WidyaDisplay {
    fn widya_display(&self) -> String;
}
impl<T: std::fmt::Debug> WidyaDisplay for T {
    fn widya_display(&self) -> String {
        let s = format!("{:?}", self);
        if s.starts_with('"') && s.ends_with('"') && s.len() >= 2 {
            s[1..s.len()-1].to_string()
        } else {
            s
        }
    }
}

macro_rules! cetak {
    ($($arg:expr),* $(,)?) => {{
        let parts: Vec<String> = vec![$( ($arg).widya_display() ),*];
        println!("{}", parts.join(" "));
    }};
}
macro_rules! tulis {
    ($($arg:expr),* $(,)?) => {{
        let parts: Vec<String> = vec![$( ($arg).widya_display() ),*];
        print!("{}", parts.join(" "));
    }};
}

fn akar(x: f64) -> f64 { x.sqrt() }
fn bulat(x: f64) -> f64 { x.round() }
fn lantai(x: f64) -> f64 { x.floor() }
fn atap(x: f64) -> f64 { x.ceil() }
fn mutlak(x: f64) -> f64 { x.abs() }
fn ke_teks<T: std::fmt::Display>(v: T) -> String { format!("{}", v) }
fn ke_angka(v: &str) -> f64 { v.trim().parse::<f64>().unwrap_or(0.0) }
fn tipe<T>(_: T) -> &'static str { "nilai" }
fn panjang<T>(v: &[T]) -> f64 { v.len() as f64 }
fn tambah<T: Clone>(v: &mut Vec<T>, item: T) { v.push(item); }

fn main() {
    cetak!("=== 📱 1. Integrasi Native Mobile & Desktop Bridge ===".to_string());
    let mut info = DapatkanInfoPerangkat();
    cetak!(("Platform: ".to_string() + info["platform".to_string() as usize]));
    cetak!(("Sistem Operasi: ".to_string() + info["os".to_string() as usize]));
    cetak!(("Arsitektur CPU: ".to_string() + info["arch".to_string() as usize]));
    cetak!((("Status Baterai: ".to_string() + string(info["baterai_persen".to_string() as usize])) + "%".to_string()));
    KirimPesanAsli("sensor/gps".to_string(), "permintaan_lokasi_terkini".to_string());
    KirimPesanAsli("notifikasi".to_string(), "Aplikasi Widya Multiplatform Berhasil Dimuat!".to_string());
    cetak!("=== 🚀 Selesai Menjalankan Native Mobile Bridge Demo ===".to_string());
}
