//! Package Manager (WPM) - Widya Package Manager
//! Manages packages, dependencies, checksums, and lockfiles

use std::collections::HashMap;
use std::fs::{self, File};
use std::io::Write;
use std::path::{Path, PathBuf};
use serde::{Deserialize, Serialize};
use sha2::{Sha256, Digest};

/// WPM configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WpmConfig {
    pub registry_url: String,
    pub cache_dir: PathBuf,
    pub packages_dir: PathBuf,
    pub global_packages: Vec<String>,
}

impl Default for WpmConfig {
    fn default() -> Self {
        Self {
            registry_url: "https://registry.widya-lang.org/api/v1".to_string(),
            cache_dir: PathBuf::from(".widya/cache"),
            packages_dir: PathBuf::from(".widya/packages"),
            global_packages: Vec::new(),
        }
    }
}

/// Package metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PackageInfo {
    pub name: String,
    pub version: String,
    pub description: String,
    pub author: String,
    pub license: String,
    pub dependencies: HashMap<String, String>,
    pub repository: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockedDependency {
    pub name: String,
    pub version: String,
    pub source: String,
    pub checksum_sha256: String,
    pub dependencies: Vec<String>,
}

/// Widya Lockfile structure (widya.lock)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PackageLock {
    pub version: u32,
    pub packages: HashMap<String, LockedDependency>,
}

impl PackageLock {
    pub fn new() -> Self {
        Self {
            version: 1,
            packages: HashMap::new(),
        }
    }

    pub fn add_locked(&mut self, dep: LockedDependency) {
        self.packages.insert(dep.name.clone(), dep);
    }

    pub fn to_toml_string(&self) -> Result<String, String> {
        let mut out = String::new();
        out.push_str("# This file is automatically @generated by Widya Package Manager (WPM).\n");
        out.push_str("# It is not intended for manual editing.\nversion = 1\n\n");

        for (name, dep) in &self.packages {
            out.push_str("[[package]]\n");
            out.push_str(&format!("name = \"{}\"\n", name));
            out.push_str(&format!("version = \"{}\"\n", dep.version));
            out.push_str(&format!("source = \"{}\"\n", dep.source));
            out.push_str(&format!("checksum = \"{}\"\n", dep.checksum_sha256));
            if !dep.dependencies.is_empty() {
                out.push_str(&format!("dependencies = {:?}\n", dep.dependencies));
            }
            out.push('\n');
        }
        Ok(out)
    }

    pub fn verify_integrity(&self) -> Result<bool, String> {
        for (name, dep) in &self.packages {
            if dep.checksum_sha256.len() != 64 {
                return Err(format!("Checksum SHA256 paket '{}' tidak valid", name));
            }
        }
        Ok(true)
    }
}

/// WPM (Widya Package Manager)
pub struct Wpm {
    pub config: WpmConfig,
}

impl Wpm {
    pub fn new(config: WpmConfig) -> Self {
        Self { config }
    }

    pub fn calculate_sha256(data: &[u8]) -> String {
        let mut hasher = Sha256::new();
        hasher.update(data);
        format!("{:x}", hasher.finalize())
    }

    /// Initialize new project
    pub fn init(&self, project_name: &str, output_dir: &Path) -> Result<PathBuf, String> {
        let project_dir = output_dir.join(project_name);

        fs::create_dir_all(&project_dir)
            .map_err(|e| format!("Failed to create project directory: {}", e))?;
        
        fs::create_dir_all(project_dir.join("src"))
            .map_err(|e| format!("Failed to create src dir: {}", e))?;

        let toml_content = format!(r#"[package]
name = "{}"
version = "0.1.0"
description = "Widya project"
author = "Developer"
license = "MIT"

[dependencies]
"#, project_name);

        let mut file = File::create(project_dir.join("widya.toml"))
            .map_err(|e| format!("Failed to create widya.toml: {}", e))?;
        file.write_all(toml_content.as_bytes())
            .map_err(|e| format!("Failed to write widya.toml: {}", e))?;

        let main_content = format!(r#"fungsi utama() {{
    cetak("Halo dari {}!");
}}
"#, project_name);

        let mut file = File::create(project_dir.join("src").join("main.wya"))
            .map_err(|e| format!("Failed to create main.wya: {}", e))?;
        file.write_all(main_content.as_bytes())
            .map_err(|e| format!("Failed to write main.wya: {}", e))?;

        // Generate initial widya.lock
        let lockfile = self.generate_lockfile(&project_dir)?;
        let lock_path = project_dir.join("widya.lock");
        fs::write(&lock_path, lockfile.to_toml_string()?)
            .map_err(|e| format!("Failed to write widya.lock: {}", e))?;

        Ok(project_dir)
    }

    pub fn generate_lockfile(&self, project_dir: &Path) -> Result<PackageLock, String> {
        let mut lock = PackageLock::new();
        let toml_path = project_dir.join("widya.toml");
        
        if toml_path.exists() {
            let content = fs::read(&toml_path).map_err(|e| e.to_string())?;
            let checksum = Self::calculate_sha256(&content);
            
            lock.add_locked(LockedDependency {
                name: "root".to_string(),
                version: "0.1.0".to_string(),
                source: "local".to_string(),
                checksum_sha256: checksum,
                dependencies: Vec::new(),
            });
        }

        Ok(lock)
    }

    pub fn add_dependency(&self, project_dir: &Path, package_name: &str, version: &str) -> Result<(), String> {
        let dummy_bytes = format!("{}-{}", package_name, version);
        let checksum = Self::calculate_sha256(dummy_bytes.as_bytes());

        let mut lock = self.generate_lockfile(project_dir)?;
        lock.add_locked(LockedDependency {
            name: package_name.to_string(),
            version: version.to_string(),
            source: format!("registry+{}", self.config.registry_url),
            checksum_sha256: checksum,
            dependencies: Vec::new(),
        });

        let lock_path = project_dir.join("widya.lock");
        fs::write(&lock_path, lock.to_toml_string()?)
            .map_err(|e| format!("Failed to write lockfile: {}", e))?;

        Ok(())
    }
}

#[cfg(test)]
pub mod tests {
    use super::*;

    #[test]
    pub fn test_wpm_init() {
        let temp_dir = std::env::temp_dir();
        let wpm = Wpm::new(WpmConfig::default());
        let result = wpm.init("test_proj_wpm", &temp_dir);
        assert!(result.is_ok());
    }

    #[test]
    pub fn test_lockfile_sha256_verification() {
        let mut lock = PackageLock::new();
        lock.add_locked(LockedDependency {
            name: "widya-http".to_string(),
            version: "1.0.0".to_string(),
            source: "registry".to_string(),
            checksum_sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855".to_string(),
            dependencies: vec![],
        });

        assert!(lock.verify_integrity().is_ok());
        let toml = lock.to_toml_string().unwrap();
        assert!(toml.contains("widya-http"));
    }
}
